### ISSUE TITLE
docker.errors.BuildError: The command '/bin/sh -c sudo groupadd -o -g 0 root' returned a non-zero code: 9

### ISSUE THREAD

**Issue by Aric3** [gitbugactions/gitbug-java#23]
I configure the environment and run commands successfully, but when i run `gitbug-java setup`, an error occured with this traceback:
Traceback (most recent call last):
  File "/root/workspace/gitbug-java/gitbug-java", line 206, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/workspace/gitbug-java/gitbug-java", line 202, in main
    fire.Fire(GitBugJavaCli)
  File "/root/.cache/pypoetry/virtualenvs/gitbug-java-BtW7_Ood-py3.11/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/gitbug-java-BtW7_Ood-py3.11/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/gitbug-java-BtW7_Ood-py3.11/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/workspace/gitbug-java/gitbug-java", line 185, in setup
    self.__setup_base_image()
  File "/root/workspace/gitbug-java/gitbug-java", line 68, in __setup_base_image
    client.images.build(path=tmp_dir, tag=runner_image, forcerm=True)
  File "/root/.cache/pypoetry/virtualenvs/gitbug-java-BtW7_Ood-py3.11/lib/python3.11/site-packages/docker/models/images.py", line 285, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c sudo groupadd -o -g 0 root' returned a non-zero code: 9
It seems like the error occured when new a group when run the docker build, but I don't know how to solve this problem. Can some one do me a favor ? Sincere thanks.

**Comment by andre15silva** [comment]
Hi @Aric3 ,

Have you checked https://github.com/gitbugactions/gitbug-java/issues/18? I believe this is the same issue you are facing.

Are you running the command under sudo?

**Comment by Aric3** [comment]
> Hi @Aric3 ,
> 
> Have you checked #18? I believe this is the same issue you are facing.
> 
> Are you running the command under sudo?

Hi! @andre15silva ,
Thank you for your reply! I'm sorry for causing trouble by not checking #18 .The situation was very similar to mine. But I've been using the root account, so I didn't running the command with a `sudo`. Then I tried to switch to a common user to rerun  all command, but this error occured :
```
aric@xxsuperserver:/root/workspace/gitbug-java$ poetry shell
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg
```

**Comment by andre15silva** [comment]
> Then I tried to switch to a common user to rerun all command, but this error occured :
> 
> ```
> aric@xxsuperserver:/root/workspace/gitbug-java$ poetry shell
> Traceback (most recent call last):
>   File "/usr/lib/command-not-found", line 28, in <module>
>     from CommandNotFound import CommandNotFound
>   File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
>     from CommandNotFound.db.db import SqliteDatabase
>   File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
>     import apt_pkg
> ModuleNotFoundError: No module named 'apt_pkg
> ```

That seems like an error outside of GitBug-Java, rather from the Poetry install missing a dependency:

Maybe you can try some of these solutions:
https://askubuntu.com/questions/480908/problem-with-update-manager-no-module-named-apt-pkg-in-ubuntu-13-10-having-i
https://stackoverflow.com/questions/56218562/how-to-fix-modulenotfounderror-no-module-named-apt-pkg

**Comment by andre15silva** [comment]
Closing this issue as it is similar to #18 . Let us know if you have any more issues @Aric3 !
